name: Go project
on: push
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            -   name: check the code
                uses: actions/checkout@v3
            -   name: set-up go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.15
            -   name: build
                run: go buuld -v ./...
            -   name: test
                run: go test -v ./...
